### ISSUE TITLE
./build.sh: /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by stanshillis** [fsprojects/Fix#35]
After creating a project using template "console" and running build.sh script on osx the following error is displayed:

> ./build.sh: /bin/bash^M: bad interpreter: No such file or directory

To get around it i removed ^M character from the script by using the following command and then it worked.

`perl -i -pe 'y|\r||d' build.sh`

Is it possible to not have that ^M character generated?

Thanks!

**Comment by spencerwi** [comment]
I've run into this before; `^M` is equivalent to CR (as in CRLF) -- it's half of what DOS/Windows considers a newline (`\r\n`), but is not part of what unices considers a newline (`\n`). 

The line parses like so on DOS/Windows:

```
#!/bin/bash

```

And like this on Unix:

```
/bin/bash<CR>

```

The fix is, in theory, pretty easy; replace CRLF with LF in `build.sh`, since it's targeted at unixes. The harder part is making sure both that [git is not set to rewrite line endings](https://help.github.com/articles/dealing-with-line-endings/) and that it doesn't accidentally get opened-and-closed in an editor that wants to rewrite the line endings.
